name: tree-segment

channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python>=3.12
  # Images manipulation
  - gdal
  - shapely

  # Point clouds manipulation
  - pdal
  - python-pdal

  # Pytorch
  - pytorch>=1.8.0
  - torchvision>=0.9.0
  - pytorch-cuda=11.8
  # - torchinfo

  # Deep Learning
  - scipy>=1.4.1
  - ultralytics
  - albumentations

  # Jupyter notebook
  - ipykernel
  - ipywidgets

  # Others
  - numpy>=1.18.5
  - matplotlib
  - opencv>=4.1.2
  - addict>=2.4.0
  - tensorboard>=2.7.0
  - pycocotools>=2.0
  - onnx>=1.10.0 # ONNX export
  - cmake
  - geojson

  # Downloading files
  - requests

  - pip
  - pip:
      # TODO: use the real tqdm package when this PR https://github.com/tqdm/tqdm/pull/1504 will be finally accepted
      # - git+https://github.com/UFO-101/tqdm.git
      - vscode-tqdm

      - laspy[lazrs,laszip]
      - pyyaml>=5.3.1

      # # Gold-YOLO
      # - cmake
      # - -r gold-yolo-requirements.txt
      - onnxsim>=0.3.6 # ONNX simplifier
      - thop # FLOPs computation
      - mmcv==1.5.0
